Dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'


urlpatterns = [
    path('',views.Dashboard.as_view(), name='dashboard')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<item_id>', views.cart_add, name='cart_add'),
    path('remove/<item_id>', views.cart_remove, name='cart_remove'),
]

myAuth/urls.py
from django.urls import path
from . import views
app_name = 'myAuth'

urlpatterns = [
    # path('', views.Index, name = "index"),
    path('login/', views.login_page, name='login'),
    # path('logout', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('Customers.urls',namespace='customer')),
    path('dashboard/', include('Dashboard.urls', namespace='dashboard')),
    path('', include('myAuth.urls', namespace='myAuth')),
    path('cart/', include('cart.urls')),
    path('',include('Product.urls', namespace='item')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'myAuth/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'myAuth/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'myAuth/css/bootstrap-reboot.css' %}" rel="stylesheet">
  <link href="{% static 'Product/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'Product/css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'Product/css/style.min.css' %}" rel="stylesheet">

  <style type="text/css">
  </style>
</head>
<body>
    <!--NavBar-->
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #ffff;">
      <div class="container">
      <a class="navbar-brand" href="/">SAFOWOOD LTD</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>

        <ul class="nav navbar-nav navbar-right ">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link dark-grey-text font-weight-bold" id="nav-my-color" href="#">Categories <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ml-3">
                <a class="nav-link dark-grey-text font-weight-bold" href="#">Contact us</a>
            </li>
            <li class="nav-item ml-3">
                <a class="nav-link dark-grey-text font-weight-bold" href="#">Welcome: {{user.email}}</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link waves-effect">
                    <span class="badge red z-depth-1 mr-1">{{ 1 }}</span>
                    <i class="fas fa-shopping-cart blue-text"></i>
                    <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                </a>
            </li>
             {% if request.user.is_superuser %}
            <li class="nav-item dropdown ml-3">
                <a class="nav-link dropdown-toggle dark-grey-text font-weight-bold" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false"><i class="fas fa-user blue-text"></i> Profile </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-cyan" aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item waves-effect waves-light" href="#">My account</a>
                    <a class="dropdown-item waves-effect waves-light" href="#">Log out</a>
                </div>
            </li>
            {% else %}
              <li class="nav-item dropdown ml-3">
                <a class="nav-link dropdown-toggle dark-grey-text font-weight-bold" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false"><i class="fas fa-user blue-text"></i> Profile </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-cyan" aria-labelledby="navbarDropdownMenuLink-4">
                    <a class="dropdown-item waves-effect waves-light" href="{%url 'dashboard:dashboard'%}">Dashboard</a>
                    <a class="dropdown-item waves-effect waves-light" href="#">My account</a>
                    <a class="dropdown-item waves-effect waves-light" href="#">Log out</a>
                </div>
            </li>
             {% endif %}
          {% else %}
            <li class="nav-item">
                <a class="nav-link waves-effect" href="{%url 'myAuth:register'%}">
                    <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link waves-effect" href="{%url 'myAuth:login'%}">
                    <span class="clearfix d-none d-sm-inline-block"> Login </span>
                </a>
            </li>
            {% endif %}
        </ul>
      </div>
    </div>
    </nav>
<!--# Checking how messages are handeled-->
        <div class="container mt-1 pt-1">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} Whalert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        {% endif %}
        </div>
         {%block content%}
        {%endblock content%}
<!--  JavaScript-->
<!--  JQuery-->
  <script type="text/javascript" src="{% static 'myAuth/js/jquery.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'myAuth/js/bootstrap.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'myAuth/js/bootstrap.js'%}"></script>
    <!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'Product/js/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'Product/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'Product/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'Product/js/mdb.min.js' %}"></script>

<script type="text/javascript">
    /* WOW.js init */
    new WOW().init();

    // SideNav Button Initialization
    $(".button-collapse").sideNav();
    // SideNav Scrollbar Initialization
    var sideNavScrollbar = document.querySelector('.custom-scrollbar');
    Ps.initialize(sideNavScrollbar);

    // Tooltips Initialization
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

  </script>
  <script>
    // Material Select Initialization
    $(document).ready(function () {
      $('.mdb-select').material_select();
    });

  </script>

</body>

templates/try.html
{%extends 'myAuth/base.html'%}
{% load staticfiles %}
{%block content%}

<div class="main-header-area header-sticky box-shadow is-sticky">
            <div class="container">
				<div class="classy-nav-container light left breakpoint-on">
					<!-- Classy Menu -->
					<nav class="classy-navbar justify-content-between" id="EduStudyNav">

						<!-- Logo -->
						<a class="nav-brand" href="/"><img src="/static/edufield/img/logo.png" alt="logo"></a>

						<!-- Navbar Toggler -->
						<div class="classy-navbar-toggler">
							<span class="navbarToggler"><span></span><span></span><span></span></span>
						</div>

						<!-- Menu -->
						<div class="classy-menu">

							<!-- close btn -->
							<div class="classycloseIcon">
								<div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
							</div>

							<!-- Nav Start -->
							<div class="classynav">
								<ul>
									<li class="cn-dropdown-item has-down pr12"><a href="#" class="active">Home</a>
										<ul class="dropdown">
                                            <li><a href="/">Home</a></li>
                                            <li><a href="/forum/blogs/blog/1/">Forum</a></li>
                                            <!-- <li><a href="index-three.html">Home Demo Three</a></li>
                                            <li class="active"><a href="index-four.html">Home Demo Four</a></li> -->
										</ul>
									<span class="dd-trigger"></span><span class="dd-arrow"></span></li>

                                     <li class="cn-dropdown-item has-down pr12"><a href="#">Account</a>
                                        <ul class="dropdown">


                                            <li><a href="/accounts/dashboard">My Dashboard</a></li>
                                            <li><a title="chats and more" href="/interact/" target="_">Enteract</a></li>
                                            <li><a href="/accounts/logout">Logout</a></li>

                                        </ul>
                                    <span class="dd-trigger"></span><span class="dd-arrow"></span></li>

                                    <li class="cn-dropdown-item has-down pr12"><a href="/courses">Courses</a>
                                        <ul class="dropdown">
                                            <li><a href="/courses/">Explore Courses</a></li>
                                            <li><a href="/tracks/">Pro Tracks</a></li>
                                            <li><a href="/courses/python/challenges">12-Day Challenge</a></li>
                                        </ul>
                                    <span class="dd-trigger"></span><span class="dd-arrow"></span></li>

                                     <li class="cn-dropdown-item has-down pr12"><a href="#">Utilities</a>
                                        <ul class="dropdown">
                                            <!--<li><a href="https://www.onlinegdb.com">Code Online</a></li>-->
                                            <li><a href="/weask/">We-ask</a></li>
                                            <li><a href="https://pywe.github.io/PywE-IDE/" target="_">Code Online</a></li>
                                            <li><a href="https://pharst.pywe.org" target="_">Phars+ Care</a></li>
                                             <li><a href="https://pharst.pywe.org/ichare/" target="_">iChare</a></li>
                                            <li><a href="/companies">Price of Services</a></li>

                                            <!--<li><a href="single-events.html">Events Details</a></li>-->
                                        </ul>
                                    <span class="dd-trigger"></span><span class="dd-arrow"></span></li>
                                    <li class="cn-dropdown-item has-down pr12"><a href="/events">Events</a>
										<ul class="dropdown">
                                            <li><a href="/events">Our Events</a></li>
										</ul>
									<span class="dd-trigger"></span><span class="dd-arrow"></span></li>

									<!-- <li><a href="#">Pages</a>
										<ul class="dropdown">
											<li><a href="about.html">About Us</a></li>
											<li><a href="#">Blog</a>
												<ul class="dropdown">
													<li><a href="blog-style-one.html">Blog Style One</a></li>
													<li><a href="blog-style-two.html">Blog Style Two</a></li>
													<li><a href="blog-style-three.html">Blog Style Three</a></li>
													<li><a href="single-blog.html">Blog Details</a></li>
												</ul>
											</li>
											<li><a href="#">Shop</a>
                                                <ul class="dropdown">
                                                    <li><a href="shop-style-one.html">Shop Style One</a></li>
                                                    <li><a href="shop-style-two.html">Shop Style Two</a></li>
                                                    <li><a href="single-shop.html">Shop Details</a></li>
                                                    <li><a href="cart.html">Cart</a></li>
                                                    <li><a href="checkout.html">Checkout</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Courses</a>
                                                <ul class="dropdown">
                                                    <li><a href="courses-style-one.html">Courses Style One</a></li>
                                                    <li><a href="courses-style-two.html">Courses Style Two</a></li>
                                                    <li><a href="single-courses.html">Courses Details</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Teacher</a>
                                                <ul class="dropdown">
                                                    <li><a href="teacher-style-one.html">Teacher Style One</a></li>
													<li><a href="teacher-style-two.html">Teacher Style Two</a></li>
													<li><a href="single-teacher.html">Teacher Details</a></li>
                                                </ul>
                                            </li>
											<li><a href="#">Events</a>
												<ul class="dropdown">
													<li><a href="event-style-one.html">Events Style One</a></li>
                                                    <li><a href="event-style-two.html">Events Style Two</a></li>
                                                    <li><a href="single-events.html">Events Details</a></li>
												</ul>
											</li>
                                            <li><a href="#">Contact</a>
												<ul class="dropdown">
													<li><a href="contact-style-one.html">Contact Style One</a></li>
                                                    <li><a href="contact-style-two.html">Contact Style Two</a></li>
												</ul>
											</li>
                                            <li><a href="admission.html">Admission</a></li>
											<li><a href="error.html">404 Error</a></li>
											<li><a href="faq.html">FAQ</a></li>
											<li><a href="login.html">Login</a></li>
											<li><a href="register.html">Register</a></li>
										</ul>
									</li> -->

									<!-- <li><a href="#">Blog</a>
										<ul class="dropdown">
											<li><a href="blog-style-one.html">Blog Style One</a></li>
                                            <li><a href="blog-style-two.html">Blog Style Two</a></li>
                                            <li><a href="blog-style-three.html">Blog Style Three</a></li>
                                            <li><a href="single-blog.html">Blog Details</a></li>
										</ul>
									</li>

									<li><a href="#">Shop</a>
										<ul class="dropdown">
											<li><a href="shop-style-one.html">Shop Style One</a></li>
                                            <li><a href="shop-style-two.html">Shop Style Two</a></li>
                                            <li><a href="single-shop.html">Shop Details</a></li>
                                            <li><a href="cart.html">Cart</a></li>
                                            <li><a href="checkout.html">Checkout</a></li>
										</ul>
									</li>
									 -->
									<li class="cn-dropdown-item has-down pr12"><a href="#">Contact</a>
										<ul class="dropdown">
											<li><a href="/interact" target="_">Enteract</a></li>
                                            <!-- <li><a href="contact-style-two.html">Contact Style Two</a></li> -->
										</ul>
									<span class="dd-trigger"></span><span class="dd-arrow"></span></li>

									<!--<li><a href="#search" class="search-btn"><i class="icofont-search-2"></i></a></li>-->
								</ul>
							</div>
							<!-- Nav End -->
						</div>
					</nav>
				</div>
			</div>
        </div>

{%endblock content%}